openapi: '3.0.3'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
servers:
  - url: 'http://localhost:9090/api'
tags:
  - name: Jedis-end-point
    description: Gestion des jedis
paths:
  /jedis:
    get:
      tags:
        - Jedis-end-point
      summary: Obtient une liste de toutes les jedis
      operationId: getJedis
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Jedi'
        '404':
          description: Not Found
    post:
      tags:
        - Jedis-end-point
      summary: Ajoute un nouvelle jedi
      operationId: addJedi
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Jedi'
      responses:
        '201':
          description: jedi crée
          headers:
            Location:
              description: URL du jedi crée
              schema:
                type: string
                format: uri
  /jedis/{id}:
    get:
      tags:
        - Jedis-end-point
      summary: Obtient un jedi
      operationId: getJedi
      parameters:
        - name: id
          in: path
          description: numéro du jedi à obtenir
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Jedi'
        '404':
          description: Not Found
      deprecated: false
components:
  schemas:
    Jedi:
      description: toutes les caractéristiques d'un jedi
      type: object
      properties:
        name:
          description: nom du jedi
          type: string
        rank:
          description: rank du jedi
          type: string
        id:
          description: numéro auto-incrémenté du jedi
          type: integer
          format: int32
      title: Jedi
